services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mi_db
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d:ro
    networks:
      - jjk-network
  jjk-rx:
    build: ./jjk-rx
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/mi_db
    volumes:
      - ./jjk-rx/out:/app/out
    networks:
      - jjk-network
  
  jjk-tx:
    build: ./jjk-tx
    networks:
      - jjk-network

  frontend:
    build: ./jjk-front
    networks:
      - jjk-network
  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - jjk-rx
      - jjk-tx
    networks:
      - jjk-network

networks:
  jjk-network:
    driver: bridge
