[package]
name = "jjk-rx"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.1"
aes-gcm = "0.10.3"
base64 = "0.22.1"
rsa = { version = "0.9.8", features = ["pem", "sha2"] }
serde = { version = "1.0.228", features = ["derive"] }
sha2 = "0.10.9"
