[package]
name = "jjk-db"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.8.5", features = ["runtime-tokio", "postgres"] }
tokio = { version = "1.49.0", features = ["rt", "macros"] }
